import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const LoginStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a0a',
  },
  safeArea: {
    flex: 1,
  },
  gradientBackground: {
    flex: 1,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  cyberLineTop: {
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(0, 212, 255, 0.2)',
    marginBottom: 40,
  },
  cyberLineBottom: {
    width: '100%',
    height: 1,
    backgroundColor: 'rgba(0, 212, 255, 0.2)',
    marginTop: 40,
  },
  logoContainer: {
    alignItems: 'center',
    marginBottom: 40,
  },
  logoTitle: {
    color: '#00d4ff',
    fontSize: 36,
    fontWeight: 'bold',
    letterSpacing: 2,
    marginBottom: 8,
    textShadowColor: 'rgba(0, 212, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  logoSubtitle: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 14,
    letterSpacing: 3,
  },
  cyberGrid: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0.05,
  },
  loginCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: 'rgba(20, 20, 20, 0.8)',
    borderRadius: 20,
    padding: 32,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.1)',
    shadowColor: '#00d4ff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  loginTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
  },
  loginSubtitle: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 32,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    marginLeft: 4,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    overflow: 'hidden',
  },
  inputIcon: {
    paddingHorizontal: 16,
  },
  textInput: {
    flex: 1,
    color: '#ffffff',
    fontSize: 16,
    paddingVertical: 16,
    paddingHorizontal: 0,
  },
  passwordToggle: {
    paddingHorizontal: 16,
  },
  loginButton: {
    backgroundColor: 'rgba(0, 212, 255, 0.1)',
    borderRadius: 12,
    paddingVertical: 18,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.2)',
    marginTop: 10,
  },
  loginButtonText: {
    color: '#00d4ff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  loginButtonDisabled: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  loginButtonTextDisabled: {
    color: 'rgba(255, 255, 255, 0.3)',
  },
  errorContainer: {
    backgroundColor: 'rgba(255, 42, 109, 0.1)',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 42, 109, 0.2)',
    marginTop: 20,
  },
  errorText: {
    color: '#ff2a6d',
    fontSize: 14,
    textAlign: 'center',
  },
  demoCredentials: {
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 12,
    padding: 16,
    marginTop: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  demoTitle: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
    textAlign: 'center',
  },
  demoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  demoLabel: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 12,
    width: 80,
  },
  demoValue: {
    color: '#00d4ff',
    fontSize: 12,
    fontFamily: 'monospace',
    flex: 1,
  },
  demoCopyButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  statusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.1)',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#00d4ff',
    marginRight: 8,
  },
  statusText: {
    color: 'rgba(255, 255, 255, 0.6)',
    fontSize: 12,
  },
  terminalOutput: {
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: 12,
    padding: 20,
    marginTop: 30,
    borderWidth: 1,
    borderColor: 'rgba(0, 212, 255, 0.1)',
  },
  terminalLine: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  terminalPrompt: {
    color: '#00d4ff',
    fontFamily: 'monospace',
    fontSize: 14,
    marginRight: 12,
    minWidth: 20,
  },
  terminalText: {
    color: 'rgba(255, 255, 255, 0.8)',
    fontFamily: 'monospace',
    fontSize: 14,
  },
});