import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f2f2f7',
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1c1c1e',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
  },
  infoCard: {
    backgroundColor: '#e8f4fd',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#007AFF',
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1c1c1e',
    marginBottom: 8,
  },
  infoText: {
    fontSize: 13,
    color: '#333',
    lineHeight: 18,
  },
  exampleCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  exampleTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1c1c1e',
    marginBottom: 8,
  },
  exampleDescription: {
    fontSize: 12,
    color: '#666',
    marginBottom: 15,
    lineHeight: 16,
  },
  inputRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  input: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: '#c7c7cc',
    borderRadius: 8,
    paddingHorizontal: 10,
    fontSize: 14,
    marginRight: 8,
  },
  addButton: {
    backgroundColor: '#34C759',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    justifyContent: 'center',
  },
  addButtonText: {
    color: 'white',
    fontSize: 12,
    fontWeight: '600',
  },
  filterContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 15,
    gap: 6,
  },
  filterButton: {
    backgroundColor: '#f2f2f7',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  activeFilter: {
    backgroundColor: '#007AFF',
  },
  filterButtonText: {
    fontSize: 12,
    color: '#333',
  },
  activeFilterText: {
    color: 'white',
    fontWeight: '600',
  },
  resultsContainer: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    marginBottom: 15,
  },
  resultTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333',
    marginBottom: 5,
  },
  resultNumbers: {
    fontSize: 12,
    color: '#666',
    marginBottom: 5,
    minHeight: 40,
  },
  resultCount: {
    fontSize: 11,
    color: '#8e8e93',
    fontStyle: 'italic',
  },
  numbersList: {
    marginBottom: 12,
  },
  numbersTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  numbersContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  numberItem: {
    backgroundColor: '#f2f2f7',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
  },
  numberText: {
    fontSize: 12,
    color: '#333',
  },
  codeExplanation: {
    fontSize: 11,
    color: '#666',
    fontStyle: 'italic',
    marginTop: 8,
  },
  factorialContainer: {
    marginBottom: 5,
  },
  factorialInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  factorialLabel: {
    fontSize: 13,
    color: '#333',
    marginRight: 10,
  },
  factorialInput: {
    width: 60,
    height: 35,
    borderWidth: 1,
    borderColor: '#c7c7cc',
    borderRadius: 6,
    paddingHorizontal: 8,
    fontSize: 14,
    textAlign: 'center',
  },
  factorialResultContainer: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  factorialEquation: {
    fontSize: 14,
    color: '#333',
    marginBottom: 5,
  },
  factorialResult: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#34C759',
  },
  calculationsContainer: {
    marginBottom: 10,
  },
  calcItem: {
    marginBottom: 10,
  },
  calcLabel: {
    fontSize: 13,
    color: '#333',
    marginBottom: 5,
  },
  calcValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1c1c1e',
    backgroundColor: '#f8f9fa',
    padding: 8,
    borderRadius: 6,
  },
  syntaxCard: {
    backgroundColor: '#1e1e1e',
    borderRadius: 12,
    padding: 15,
    marginBottom: 15,
  },
  syntaxTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 10,
  },
  codeBlock: {
    backgroundColor: '#252525',
    borderRadius: 6,
    padding: 10,
  },
  codeComment: {
    color: '#6A9955',
    fontSize: 10,
    marginBottom: 5,
    fontStyle: 'italic',
  },
  code: {
    color: '#d4d4d4',
    fontSize: 11,
    lineHeight: 16,
    fontFamily: 'monospace',
  },
  buttonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  resetButton: {
    backgroundColor: '#8E8E93',
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginRight: 8,
  },
  resetButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  backButton: {
    backgroundColor: '#007AFF',
    flex: 1,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginLeft: 8,
  },
  backButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '600',
  },
  tipCard: {
    backgroundColor: '#fff3cd',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#ffc107',
  },
  tipText: {
    fontSize: 12,
    color: '#856404',
    textAlign: 'center',
  },
});